//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://beans.soap.xws_proj.booking_site", ConfigurationName="AccommodationsPort")]
public interface AccommodationsPort
{
    
    // CODEGEN: Generating message contract since the operation GetAllAccommodations is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetAllAccommodationsResponse1 GetAllAccommodations(GetAllAccommodationsRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<GetAllAccommodationsResponse1> GetAllAccommodationsAsync(GetAllAccommodationsRequest1 request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://beans.soap.xws_proj.booking_site")]
public partial class GetAllAccommodationsRequest
{
    
    private string auth_tokenField;
    
    private long idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string auth_token
    {
        get
        {
            return this.auth_tokenField;
        }
        set
        {
            this.auth_tokenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public long id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans.soap.xws_proj.booking_site")]
public partial class Accommodation
{
    
    private long idField;
    
    private string addressField;
    
    private int categoryField;
    
    private string typeField;
    
    private string descriptionField;
    
    private string image_uriField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public long id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public int category
    {
        get
        {
            return this.categoryField;
        }
        set
        {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string image_uri
    {
        get
        {
            return this.image_uriField;
        }
        set
        {
            this.image_uriField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans.soap.xws_proj.booking_site")]
public partial class Accommodations
{
    
    private Accommodation[] accommodationField;
    
    private string auth_tokenField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Accommodation", Order=0)]
    public Accommodation[] Accommodation
    {
        get
        {
            return this.accommodationField;
        }
        set
        {
            this.accommodationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string auth_token
    {
        get
        {
            return this.auth_tokenField;
        }
        set
        {
            this.auth_tokenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://beans.soap.xws_proj.booking_site")]
public partial class GetAllAccommodationsResponse
{
    
    private Accommodations accommodationsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public Accommodations Accommodations
    {
        get
        {
            return this.accommodationsField;
        }
        set
        {
            this.accommodationsField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetAllAccommodationsRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://beans.soap.xws_proj.booking_site", Order=0)]
    public GetAllAccommodationsRequest GetAllAccommodationsRequest;
    
    public GetAllAccommodationsRequest1()
    {
    }
    
    public GetAllAccommodationsRequest1(GetAllAccommodationsRequest GetAllAccommodationsRequest)
    {
        this.GetAllAccommodationsRequest = GetAllAccommodationsRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetAllAccommodationsResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://beans.soap.xws_proj.booking_site", Order=0)]
    public GetAllAccommodationsResponse GetAllAccommodationsResponse;
    
    public GetAllAccommodationsResponse1()
    {
    }
    
    public GetAllAccommodationsResponse1(GetAllAccommodationsResponse GetAllAccommodationsResponse)
    {
        this.GetAllAccommodationsResponse = GetAllAccommodationsResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface AccommodationsPortChannel : AccommodationsPort, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AccommodationsPortClient : System.ServiceModel.ClientBase<AccommodationsPort>, AccommodationsPort
{
    
    public AccommodationsPortClient()
    {
    }
    
    public AccommodationsPortClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AccommodationsPortClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AccommodationsPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AccommodationsPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetAllAccommodationsResponse1 AccommodationsPort.GetAllAccommodations(GetAllAccommodationsRequest1 request)
    {
        return base.Channel.GetAllAccommodations(request);
    }
    
    public GetAllAccommodationsResponse GetAllAccommodations(GetAllAccommodationsRequest GetAllAccommodationsRequest)
    {
        GetAllAccommodationsRequest1 inValue = new GetAllAccommodationsRequest1();
        inValue.GetAllAccommodationsRequest = GetAllAccommodationsRequest;
        GetAllAccommodationsResponse1 retVal = ((AccommodationsPort)(this)).GetAllAccommodations(inValue);
        return retVal.GetAllAccommodationsResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetAllAccommodationsResponse1> AccommodationsPort.GetAllAccommodationsAsync(GetAllAccommodationsRequest1 request)
    {
        return base.Channel.GetAllAccommodationsAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetAllAccommodationsResponse1> GetAllAccommodationsAsync(GetAllAccommodationsRequest GetAllAccommodationsRequest)
    {
        GetAllAccommodationsRequest1 inValue = new GetAllAccommodationsRequest1();
        inValue.GetAllAccommodationsRequest = GetAllAccommodationsRequest;
        return ((AccommodationsPort)(this)).GetAllAccommodationsAsync(inValue);
    }
}
