//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://beans.soap.xws_proj.booking_site", ConfigurationName="LoginPort")]
public interface LoginPort
{
    
    // CODEGEN: Generating message contract since the operation GetLogin is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetLoginResponse1 GetLogin(GetLoginRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<GetLoginResponse1> GetLoginAsync(GetLoginRequest1 request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://beans.soap.xws_proj.booking_site")]
public partial class GetLoginRequest
{
    
    private string emailField;
    
    private string passwordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans.soap.xws_proj.booking_site")]
public partial class AgentDetails
{
    
    private long idField;
    
    private string nameField;
    
    private string emailField;
    
    private string addressField;
    
    private string tinField;
    
    private string auth_tokenField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public long id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string tin
    {
        get
        {
            return this.tinField;
        }
        set
        {
            this.tinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string auth_token
    {
        get
        {
            return this.auth_tokenField;
        }
        set
        {
            this.auth_tokenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://beans.soap.xws_proj.booking_site")]
public partial class GetLoginResponse
{
    
    private AgentDetails agentDetailsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public AgentDetails AgentDetails
    {
        get
        {
            return this.agentDetailsField;
        }
        set
        {
            this.agentDetailsField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetLoginRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://beans.soap.xws_proj.booking_site", Order=0)]
    public GetLoginRequest GetLoginRequest;
    
    public GetLoginRequest1()
    {
    }
    
    public GetLoginRequest1(GetLoginRequest GetLoginRequest)
    {
        this.GetLoginRequest = GetLoginRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetLoginResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://beans.soap.xws_proj.booking_site", Order=0)]
    public GetLoginResponse GetLoginResponse;
    
    public GetLoginResponse1()
    {
    }
    
    public GetLoginResponse1(GetLoginResponse GetLoginResponse)
    {
        this.GetLoginResponse = GetLoginResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface LoginPortChannel : LoginPort, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class LoginPortClient : System.ServiceModel.ClientBase<LoginPort>, LoginPort
{
    
    public LoginPortClient()
    {
    }
    
    public LoginPortClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public LoginPortClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LoginPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LoginPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetLoginResponse1 LoginPort.GetLogin(GetLoginRequest1 request)
    {
        return base.Channel.GetLogin(request);
    }
    
    public GetLoginResponse GetLogin(GetLoginRequest GetLoginRequest)
    {
        GetLoginRequest1 inValue = new GetLoginRequest1();
        inValue.GetLoginRequest = GetLoginRequest;
        GetLoginResponse1 retVal = ((LoginPort)(this)).GetLogin(inValue);
        return retVal.GetLoginResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetLoginResponse1> LoginPort.GetLoginAsync(GetLoginRequest1 request)
    {
        return base.Channel.GetLoginAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetLoginResponse1> GetLoginAsync(GetLoginRequest GetLoginRequest)
    {
        GetLoginRequest1 inValue = new GetLoginRequest1();
        inValue.GetLoginRequest = GetLoginRequest;
        return ((LoginPort)(this)).GetLoginAsync(inValue);
    }
}
