//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XwsAgent.BackendService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://beans.soap.xws_proj.booking_site", ConfigurationName="BackendService.LoginPort")]
    public interface LoginPort {
        
        // CODEGEN: Generating message contract since the operation GetLogin is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        XwsAgent.BackendService.GetLoginResponse1 GetLogin(XwsAgent.BackendService.GetLoginRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<XwsAgent.BackendService.GetLoginResponse1> GetLoginAsync(XwsAgent.BackendService.GetLoginRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://beans.soap.xws_proj.booking_site")]
    public partial class GetLoginRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans.soap.xws_proj.booking_site")]
    public partial class AgentDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        private string emailField;
        
        private string addressField;
        
        private string tinField;
        
        private string auth_tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string tin {
            get {
                return this.tinField;
            }
            set {
                this.tinField = value;
                this.RaisePropertyChanged("tin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string auth_token {
            get {
                return this.auth_tokenField;
            }
            set {
                this.auth_tokenField = value;
                this.RaisePropertyChanged("auth_token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://beans.soap.xws_proj.booking_site")]
    public partial class GetLoginResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AgentDetails agentDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AgentDetails AgentDetails {
            get {
                return this.agentDetailsField;
            }
            set {
                this.agentDetailsField = value;
                this.RaisePropertyChanged("AgentDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://beans.soap.xws_proj.booking_site", Order=0)]
        public XwsAgent.BackendService.GetLoginRequest GetLoginRequest;
        
        public GetLoginRequest1() {
        }
        
        public GetLoginRequest1(XwsAgent.BackendService.GetLoginRequest GetLoginRequest) {
            this.GetLoginRequest = GetLoginRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://beans.soap.xws_proj.booking_site", Order=0)]
        public XwsAgent.BackendService.GetLoginResponse GetLoginResponse;
        
        public GetLoginResponse1() {
        }
        
        public GetLoginResponse1(XwsAgent.BackendService.GetLoginResponse GetLoginResponse) {
            this.GetLoginResponse = GetLoginResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginPortChannel : XwsAgent.BackendService.LoginPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginPortClient : System.ServiceModel.ClientBase<XwsAgent.BackendService.LoginPort>, XwsAgent.BackendService.LoginPort {
        
        public LoginPortClient() {
        }
        
        public LoginPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XwsAgent.BackendService.GetLoginResponse1 XwsAgent.BackendService.LoginPort.GetLogin(XwsAgent.BackendService.GetLoginRequest1 request) {
            return base.Channel.GetLogin(request);
        }
        
        public XwsAgent.BackendService.GetLoginResponse GetLogin(XwsAgent.BackendService.GetLoginRequest GetLoginRequest) {
            XwsAgent.BackendService.GetLoginRequest1 inValue = new XwsAgent.BackendService.GetLoginRequest1();
            inValue.GetLoginRequest = GetLoginRequest;
            XwsAgent.BackendService.GetLoginResponse1 retVal = ((XwsAgent.BackendService.LoginPort)(this)).GetLogin(inValue);
            return retVal.GetLoginResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XwsAgent.BackendService.GetLoginResponse1> XwsAgent.BackendService.LoginPort.GetLoginAsync(XwsAgent.BackendService.GetLoginRequest1 request) {
            return base.Channel.GetLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<XwsAgent.BackendService.GetLoginResponse1> GetLoginAsync(XwsAgent.BackendService.GetLoginRequest GetLoginRequest) {
            XwsAgent.BackendService.GetLoginRequest1 inValue = new XwsAgent.BackendService.GetLoginRequest1();
            inValue.GetLoginRequest = GetLoginRequest;
            return ((XwsAgent.BackendService.LoginPort)(this)).GetLoginAsync(inValue);
        }
    }
}
